# Generated by Django 4.1.5 on 2023-05-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_company_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("cost", models.IntegerField()),
                ("manufacture_date", models.DateField()),
                ("expiry_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Cloth",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school.product",),
        ),
        migrations.CreateModel(
            name="Electronics",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school.product",),
        ),
        migrations.CreateModel(
            name="Vegitable",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school.product",),
        ),
    ]
