# Generated by Django 4.1.5 on 2023-05-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_product_cloth_electronics_vegitable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=30)),
                ("book_price", models.IntegerField()),
                ("book_pages", models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="cloth",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="electronics",
            options={"ordering": ["manufacture_date"]},
        ),
        migrations.AlterModelOptions(
            name="vegitable",
            options={"ordering": ["name"]},
        ),
    ]
