# Generated by Django 4.1.5 on 2023-05-13 04:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_book_alter_cloth_options_alter_electronics_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="book",
            managers=[
                ("books", django.db.models.manager.Manager()),
            ],
        ),
    ]
